runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  - .env

env_variables:
 
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:RakCSny7reRPHPObAf+yfahPa2bFZZMib40JGzDVidU=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: wholesome
  DB_USERNAME: root
  DB_PASSWORD: Concord@123

  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/flexlaravel:us-central1:wholesomedb"


beta_settings:
    cloud_sql_instances: "flexlaravel:us-central1:wholesomedb"
